version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - generator
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/abstractions/ruby"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - Ruby
- package-ecosystem: composer
  directory: "/abstractions/php"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - PHP
- package-ecosystem: nuget
  directory: "/cli/commons"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - CLI
