name: PHP abstractions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['abstractions/php/**', '.github/workflows/**']
  pull_request:
    paths: ['abstractions/php/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./abstractions/php
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: composer install
        working-directory: ${{ env.relativePath }}
      - name: Clear PHPStan cache
        run: ./vendor/bin/phpstan -clear-result-cache
        working-directory: ${{ env.relativePath }}
      - name: Run static analysis
        run: ./vendor/bin/phpstan
        working-directory: ${{ env.relativePath }}
      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-text
        working-directory: ${{ env.relativePath }}
