name: Build VSCode extension

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "abstractions/**"
      - "authentication/**"
      - "serialization/**"
      - "http/**"
      - "**.md"
      - ".vscode/**"
      - "**.svg"
  pull_request:
    paths-ignore:
      - "abstractions/**"
      - "authentication/**"
      - "serialization/**"
      - "http/**"
      - "**.md"
      - ".vscode/**"
      - "**.svg"

jobs:
  build_extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          view_top: 1
      - run: scripts/update-vscode-releases.ps1 -version ${{ steps.last_release.outputs.tag_name }} -filePath ./vscode/microsoft-kiota/package.json -online
        shell: pwsh
      - name: Install dependencies
        run: npm ci
        working-directory: vscode/microsoft-kiota
      - run: npm run package
        working-directory: vscode/microsoft-kiota
      - run: npm i -g @vscode/vsce
      - run: vsce package
        working-directory: vscode/microsoft-kiota
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: vscode/microsoft-kiota/*.vsix
