name: .NET

on:
  push:
    branches: [ main ]
    path-ignore: ['abstractions/**', '**.md', '.vscode/**']
  pull_request:
    path-ignore: ['abstractions/**', '**.md', '.vscode/**']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore kiota.sln
    - name: Build
      run: dotnet build kiota.sln --no-restore
    - name: Test
      run: dotnet test kiota.sln --no-build --verbosity normal /p:CollectCoverage=true
    - name: Install report generator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: Generate coverage report
      run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:./reports/coverage
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: reports/coverage
