name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled, reopened]
  pull_request:
    types: [opened, labeled, reopened]

env:
  GH_TOKEN: ${{ secrets.ISSUES_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Set Java project info
        run: gh project item-add 25 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Java')
        shell: pwsh
      - name: Set Go project
        run: gh project item-add 26 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Go')
        shell: pwsh
      - name: Set Ruby project
        run: gh project item-add 38 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Ruby')
        shell: pwsh
      - name: Set PHP project
        run: gh project item-add 33 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'PHP')
        shell: pwsh
      - name: Set Python project
        run: gh project item-add 34 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Python')
        shell: pwsh
      - name: Set TypeScript project
        run: gh project item-add 21 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'TypeScript')
        shell: pwsh
      - name: Set CSharp project
        run: gh project item-add 28 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'CSharp')
        shell: pwsh
      - name: Set Generator project
        run: gh project item-add 220 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'generator')
        shell: pwsh
      - name: Set CLI project
        run: gh project item-add 23 --owner "microsoftgraph" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'CLI')
        shell: pwsh
