name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled, reopened]
  pull_request:
    types: [opened, labeled, reopened]

env:
  GITHUB_TOKEN: ${{ secrets.ISSUES_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Set Java project info
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Java')
        env:
          project_nb: "25"
          org: "microsoftgraph"
      - name: Set Go project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Go')
        env:
          project_nb: "26"
          org: "microsoftgraph"
      - name: Set Ruby project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Ruby')
        env:
          project_nb: "38"
          org: "microsoftgraph"
      - name: Set PHP project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'PHP')
        env:
          project_nb: "33"
          org: "microsoftgraph"
      - name: Set Python project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'Python')
        env:
          project_nb: "34"
          org: "microsoftgraph"
      - name: Set TypeScript project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'TypeScript')
        env:
          project_nb: "21"
          org: "microsoftgraph"
      - name: Set CSharp project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'CSharp')
        env:
          project_nb: "28"
          org: "microsoftgraph"
      - name: Set Generator project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'generator')
        env:
          project_nb: "220"
          org: "microsoft"
      - name: Set CLI project
        run: gh project item-add $PROJECT_NB --owner "$ORG" --url "${{ github.event.issue.html_url}}"
        if: contains(github.event.issue.labels.*.name, 'CLI')
        env:
          project_nb: "23"
          org: "microsoftgraph"
